authentik:
  secret_key: "Sp4rti4te!$authentik-secret-key-lab"
  postgresql:
    host: "10.10.1.30"
    name: "authentik"
    user: "dbadmin"
    password: "Sp4rti4te!$"
    port: 5432
  redis:
    host: "authentik-redis-master"
    port: 6379

postgresql:
  enabled: false

redis:
  enabled: true

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - authentik.lab.local
    paths:
      - /
    pathType: Prefix

worker:
  replicas: 1
